# Generated by Django 4.2.20 on 2025-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="btc_wallet",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse Bitcoin"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="eth_erc20_wallet",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse ETH (ERC20)"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="usdt_trc20_wallet",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse USDT (TRC20)"),
        ),
    ]
