# Generated by Django 4.2.20 on 2025-05-09 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_userprofile_btc_wallet_userprofile_eth_erc20_wallet_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Téléphone"),
                            ("2fa", "Authentification à deux facteurs"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "code de vérification",
                "verbose_name_plural": "codes de vérification",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="display_mode",
            field=models.CharField(
                choices=[("light", "Clair"), ("dark", "Sombre"), ("system", "Système")],
                default="light",
                max_length=10,
                verbose_name="Mode d'affichage",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("de", "Deutsch"),
                ],
                default="fr",
                max_length=5,
                verbose_name="Langue préférée",
            ),
        ),
        migrations.DeleteModel(
            name="AccountProfile",
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
