# Generated by Django 4.2.20 on 2025-05-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_alter_user_created_at_alter_userprofile_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supabase_id",
            field=models.CharField(
                blank=True,
                max_length=36,
                null=True,
                unique=True,
                verbose_name="Identifiant Supabase",
            ),
        ),
    ]
