# Generated by Django 4.2.20 on 2025-05-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_supabase_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VerificationCode",
        ),
    ]
