# Generated by Django 4.2.20 on 2025-05-12 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhiteLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Site Name")),
                (
                    "domain",
                    models.CharField(max_length=255, unique=True, verbose_name="Domain"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="whitelabel/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(default="#7C4DFF", max_length=7, verbose_name="Primary Color"),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#FF4D94", max_length=7, verbose_name="Secondary Color"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta Description"),
                ),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=255, verbose_name="Meta Keywords"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whitelabel_sites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "White Label Site",
                "verbose_name_plural": "White Label Sites",
                "ordering": ["-created_at"],
            },
        ),
    ]
