# Generated by Django 4.2.20 on 2025-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whitelabel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelabel",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="whitelabel/favicons/",
                verbose_name="Favicon",
            ),
        ),
    ]
