# Generated by Django 4.2.20 on 2025-05-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whitelabel", "0002_whitelabel_favicon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whitelabel",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="whitelabel",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="whitelabel",
            name="meta_title",
        ),
    ]
