# Generated by Django 4.2.20 on 2025-05-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0004_marketingmaterial_paymentmethod"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliatelevel",
            options={
                "ordering": ["min_earnings"],
                "verbose_name": "niveau d'affiliation",
                "verbose_name_plural": "niveaux d'affiliation",
            },
        ),
        migrations.AlterModelOptions(
            name="affiliateprofile",
            options={
                "verbose_name": "profil d'affilié",
                "verbose_name_plural": "profils d'affiliés",
            },
        ),
        migrations.AlterModelOptions(
            name="badge",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AlterModelOptions(
            name="challenge",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="challengeprogress",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "progression de défi",
                "verbose_name_plural": "progressions de défis",
            },
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="requirements",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="rewards",
        ),
        migrations.AddField(
            model_name="affiliatelevel",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AddField(
            model_name="affiliatelevel",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="affiliatelevel",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="levels/icons/"),
        ),
        migrations.AddField(
            model_name="badge",
            name="category",
            field=models.CharField(
                choices=[
                    ("referral", "Parrainage"),
                    ("earning", "Gains"),
                    ("engagement", "Engagement"),
                    ("special", "Spécial"),
                ],
                default="referral",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="category",
            field=models.CharField(
                choices=[
                    ("referral", "Parrainage"),
                    ("earning", "Gains"),
                    ("engagement", "Engagement"),
                    ("special", "Spécial"),
                ],
                default="referral",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="reward_bonus",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="challenge",
            name="reward_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="challenge",
            name="target",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="challenge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="custom_css",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="custom_js",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="dns_verification_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="dns_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="whitelabels/favicons/"),
        ),
        migrations.AlterField(
            model_name="affiliatelevel",
            name="name",
            field=models.CharField(
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Argent"),
                    ("gold", "Or"),
                    ("platinum", "Platine"),
                    ("diamond", "Diamant"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="type",
            field=models.CharField(
                choices=[
                    ("daily", "Quotidien"),
                    ("weekly", "Hebdomadaire"),
                    ("monthly", "Mensuel"),
                    ("special", "Spécial"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="challengeprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de complétion"),
        ),
        migrations.AlterField(
            model_name="challengeprogress",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Complété"),
        ),
        migrations.AlterField(
            model_name="challengeprogress",
            name="progress",
            field=models.IntegerField(default=0, verbose_name="Progression"),
        ),
    ]
