# Generated by Django 4.2.20 on 2025-05-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0005_alter_affiliatelevel_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="challengeprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="challengeprogress",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="challengeprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="affiliateprofile",
            name="achievements",
        ),
        migrations.DeleteModel(
            name="Achievement",
        ),
        migrations.DeleteModel(
            name="Challenge",
        ),
        migrations.DeleteModel(
            name="ChallengeProgress",
        ),
    ]
