# Generated by Django 4.2.20 on 2025-05-12 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("affiliate", "0007_banner_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Bannière",
                "verbose_name_plural": "Bannières",
            },
        ),
        migrations.AddField(
            model_name="banner",
            name="clicks_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de clics"),
        ),
        migrations.AddField(
            model_name="banner",
            name="html_code",
            field=models.TextField(blank=True, null=True, verbose_name="Code HTML"),
        ),
        migrations.AddField(
            model_name="banner",
            name="partner_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Email du partenaire",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="type",
            field=models.CharField(
                choices=[
                    ("personal", "Bannière personnelle"),
                    ("partner", "Bannière partenaire"),
                ],
                default="personal",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de vues"),
        ),
        migrations.AddField(
            model_name="commission",
            name="admin_note",
            field=models.TextField(blank=True, verbose_name="Note administrative"),
        ),
        migrations.AddField(
            model_name="commission",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Approuvée le"),
        ),
        migrations.AddField(
            model_name="commission",
            name="commission_type",
            field=models.CharField(
                choices=[("direct", "Directe"), ("indirect", "Indirecte")],
                default="direct",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="description",
            field=models.CharField(blank=True, max_length=255, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="commission",
            name="gross_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Montant brut"
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="rate_applied",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux appliqué (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="reference_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="ID de référence"),
        ),
        migrations.AddField(
            model_name="commission",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Raison du rejet"),
        ),
        migrations.AddField(
            model_name="commission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_commissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="meta_description",
            field=models.TextField(blank=True, verbose_name="Description meta"),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Titre meta"),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="signups_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'inscriptions"),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="visits_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de visites"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="banners/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="link",
            field=models.URLField(blank=True, verbose_name="Lien"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banners",
                to="affiliate.whitelabel",
                verbose_name="Site White Label",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant"),
        ),
        migrations.AlterField(
            model_name="commission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
        ),
        migrations.AlterField(
            model_name="commission",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Payée le"),
        ),
        migrations.AlterField(
            model_name="commission",
            name="referral",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="affiliate.referral",
                verbose_name="Parrainage",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvée"),
                    ("paid", "Payée"),
                    ("rejected", "Rejetée"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID de transaction"
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ambassadeur",
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="white_labels",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ambassadeur",
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="custom_css",
            field=models.TextField(blank=True, null=True, verbose_name="CSS personnalisé"),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Domaine personnalisé",
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="custom_js",
            field=models.TextField(blank=True, null=True, verbose_name="JavaScript personnalisé"),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="dns_verification_code",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Code de vérification DNS",
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="dns_verified",
            field=models.BooleanField(default=False, verbose_name="DNS vérifié"),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="domain",
            field=models.CharField(max_length=255, unique=True, verbose_name="Domaine"),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="whitelabels/favicons/",
                verbose_name="Favicon",
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="whitelabels/logos/",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom du site"),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="primary_color",
            field=models.CharField(
                default="#7C4DFF", max_length=7, verbose_name="Couleur principale"
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="secondary_color",
            field=models.CharField(
                default="#FF4D94", max_length=7, verbose_name="Couleur secondaire"
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(fields=["status"], name="affiliate_c_status_9d969a_idx"),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(fields=["user", "status"], name="affiliate_c_user_id_04c501_idx"),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(fields=["created_at"], name="affiliate_c_created_39bdb6_idx"),
        ),
    ]
