# Generated by Django 4.2.20 on 2025-05-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0008_alter_banner_options_banner_clicks_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="white_label",
        ),
        migrations.DeleteModel(
            name="MarketingMaterial",
        ),
        migrations.RemoveField(
            model_name="affiliateprofile",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="affiliateprofile",
            name="level",
        ),
        migrations.DeleteModel(
            name="AffiliateLevel",
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
