# Generated by Django 4.2.20 on 2025-05-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "affiliate",
            "0009_remove_banner_white_label_delete_marketingmaterial_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whitelabel",
            name="custom_css",
        ),
        migrations.RemoveField(
            model_name="whitelabel",
            name="custom_js",
        ),
        migrations.RemoveField(
            model_name="whitelabel",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="whitelabel",
            name="meta_title",
        ),
    ]
