# Generated by Django 4.2.20 on 2025-05-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0010_remove_whitelabel_custom_css_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
